version: 3.0.{build}
pull_requests:
  do_not_increment_build_number: true
skip_tags: true
image: Visual Studio 2017
configuration:
- Debug 4.5
- Debug 4.5.1
- Release 4.5
- Release 4.5.1
clone_depth: 1
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
nuget:
  disable_publish_on_pr: true
before_build:
- ps: nuget restore
build:
  publish_nuget: true
  parallel: true
  verbosity: minimal
test:
  assemblies:
    only:
    - '**\*.Specs.dll'